### ISSUE TITLE
HTML file 404 error

### ISSUE THREAD

**Issue by ajmeek** [OpenNeuroDerivatives/ds000212-fmriprep#1]
Hello,

I'm attempting to use your dataset for a research paper I'm currently working on. I've download it with datalad into my work area in Pycharm. However, when I click on the html reports that fmriprep outputs for a single subject (ex: sub-03.html), I keep getting a 404 error. Pycharm says that it's an invalid symlink. When I look in the files in the repo here, I notice that they're pointing to a git annex area. I was hoping that this area would also be downloaded by datalad but it seems that that wasn't the case.

Do you have any workarounds here or have you encountered this issue before? Or, is there a way you can point me to that I can get the data the html files are referring to?

Thank you,
Austin

**Comment by effigies** [comment]
You need to download the dataset using datalad. Probably the best quickstart guide is https://handbook.datalad.org/en/latest/usecases/openneuro.html

**Comment by ajmeek** [comment]
Thank you! That was a super fast reply. I'll go through this and it should solve my issues, really appreciate it.
